apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- jenkins-namespace.yaml
#- jenkins-pvc.yaml
#- jenkins-gluster-deployment.yaml
#- jenkins-ceph-deployment.yaml
- jenkins-longhorn-deployment.yaml
- jenkins-service.yaml
- jenkins-service-jnlp.yaml
- jenkins-ingress.yaml

namespace: jenkins

commonLabels:
  app: jenkins
