apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-jenkins
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-ceph-block
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi

