apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-jenkins
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi

