apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-jenkins
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

